  - name: Checkout ISPyB project
    git:
        repo: https://github.com/ispyb/ISPyB.git
        dest: "{{ ispyb_home }}"
    ignore_errors: yes

  - name: Change ownership to vagrant
    file:
        path: "{{ ispyb_home }}"
        owner: vagrant
        group: vagrant
        recurse: yes

# Latest version includes a method to initialize dependencies from maven
  - name: Install ISPyB local dependencies
    become_user: vagrant
    shell: |
        cd {{ ispyb_home }}/dependencies
        mvn initialize

  - name: Install ispyb configuration
    template:
      src: files/settings.xml.j2
      dest: "{{ ispyb_home }}/configuration/settings.xml"
      owner: vagrant
      group: vagrant
