  - name: Checkout ISPyB project
    git:
        repo: http://github.com/ispyb/ISPyB.git
        dest: "{{ ispyb_home }}"
    ignore_errors: yes

  - name: Change ownership to vagrant
    file:
        path: "{{ ispyb_home }}"
        owner: vagrant
        group: vagrant
        recurse: yes

  # - name: Install ISPyB local dependencies
  #   become_user: vagrant
  #   shell: |
  #       cd {{ ispyb_home }}/dependencies
  #       mvn install:install-file -Dfile=securityfilter.jar -DgroupId=securityfilter -DartifactId=securityfilter -Dversion=1.0 -Dpackaging=jar
  #       mvn install:install-file -Dfile=securityaes.jar -DgroupId=securityaes -DartifactId=securityaes -Dversion=1.0 -Dpackaging=jar
  #       mvn install:install-file -Dfile=jhdf.jar -DgroupId=jhdf -DartifactId=jhdf -Dversion=1.0 -Dpackaging=jar
  #       mvn install:install-file -Dfile=jhdf5.jar -DgroupId=jhdf5 -DartifactId=jhdf5 -Dversion=1.0 -Dpackaging=jar
  #       mvn install:install-file -Dfile=jhdf5obj.jar -DgroupId=jhdf5obj -DartifactId=jhdf5obj -Dversion=1.0 -Dpackaging=jar
  #       mvn install:install-file -Dfile=jhdfobj.jar -DgroupId=jhdfobj -DartifactId=jhdfobj -Dversion=1.0 -Dpackaging=jar
  #       mvn install:install-file -Dfile=Struts-Layout-1.2.jar -DgroupId=struts-layout -DartifactId=struts-layout -Dversion=1.2 -Dpackaging=jar
  #       mvn install:install-file -Dfile=ojdbc6.jar -DgroupId=ojdbc6 -DartifactId=ojdbc6 -Dversion=1.0 -Dpackaging=jar
  #       mvn install:install-file -Dfile=ispyb-WSclient-userportal-gen-1.3.jar -DgroupId=ispyb -DartifactId=ispyb-WSclient-userportal-gen -Dversion=1.3 -Dpackaging=jar
# LAtest version includes a method to initialize dependencies from maven
  - name: Install ISPyB local dependencies
    become_user: vagrant
    shell: |
        cd {{ ispyb_home }}/dependencies
        mvn initialize

  - name: Install Wildfly configuration
    template:
      src: files/standalone.xml.j2
      dest: "{{ wildfly_home }}/standalone/configuration/standalone.xml"
      owner: vagrant
      group: vagrant

  - name: Install ispyb configuration
    template:
      src: files/settings.xml.j2
      dest: "{{ ispyb_home }}/configuration/settings.xml"
      owner: vagrant
      group: vagrant

  - name: Ensure wildfly configuration directory exists
    file:
      path: "{{ wildfly_home }}/standalone/configuration/props/"
      state: directory
      mode: 0755

  - name: Install wildfly authentication files
    file:
      src: files/users.properties
      dest: "{{ wildfly_home }}/standalone/configuration/props/"
      owner: vagrant
      group: vagrant
    ignore_errors: true

  - name: Install wildfly authentication files
    file:
      src: files/roles.properties
      dest: "{{ wildfly_home }}/standalone/configuration/props/"
      owner: vagrant
      group: vagrant
    ignore_errors: true
